Add some informations about commands
darlanmendonca/bash-basics pull request #10
Opened 2016-10-05 11:22 UTC by OdineiRibeiro

Adicionei informações sobre como criar pastas, criar arquivos e mover arquivos com espaços e como copiar todo o conteúdo de um diretório para outro.

2016-10-05 20:16 UTC, khaosdoctor approved these changes
Muito bom, as dicas vão ajudar bastante :)

2016-10-05 20:17 UTC, khaosdoctor commented
Só preciso ver se isso não vai conflitar com a #15 porque vamos mudar a estrutura

2016-10-05 21:45 UTC, OdineiRibeiro commented
@khaosdoctor, eu vou precisar fazer um commit para cada comando desse PR. Então, assim que o #15 for mergeado, eu refaço o PR da forma correta!

2016-10-06 02:58 UTC, khaosdoctor commented
Ok vou mesclar o #15 então aqui, e ai você já pode abrir uma nova adição nessa PR

2016-10-06 02:58 UTC, khaosdoctor requested changes
Aguardar a publicação da #15

2016-10-06 03:00 UTC, khaosdoctor commented
@OdineiRibeiro Pode tocar!

2016-10-06 11:07 UTC, OdineiRibeiro commented
@khaosdoctor, criei os PR's seguindo o guideline. Não sei se fiz certo (é a minha primeira contribuição para projetos open aqui no github :tada:), qualquer coisa, só mandar que eu arrumo aqui!

Os PR's são #16 #17 #18 #19 #20 #21 #22 #23

2016-10-06 15:56 UTC, khaosdoctor commented
Fechando então ;)

2016-10-06 15:56 UTC, closed without merging